package com.example.studysync_project.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import com.google.firebase.firestore.PropertyName;

/**
 * Represents a quiz that contains multiple questions
 */
@Entity(tableName = "quizzes")
public class Quiz {
    @PrimaryKey
    @NonNull
    public String quizId;

    public String userId;  // Quiz creator/owner
    public String title;
    public String description;
    public int totalQuestions;
    public double passingScore;  // Percentage (e.g., 60.0 for 60%)

    @PropertyName("created_at")
    public long createdAt;

    @PropertyName("updated_at")
    public long updatedAt;

    public String subject;  // Math, Science, History, etc.
    public int difficulty;  // 1-5 scale
    public String moduleId; // Optional link to source StudyModule
    public boolean isArchived;

    // Constructors
    public Quiz() {
        this.quizId = "";
    }

    public Quiz(String userId, String title, String description, int totalQuestions,
                double passingScore, String subject, int difficulty) {
        this.quizId = ""; // Usually generated by Firestore or Room
        this.userId = userId;
        this.title = title;
        this.description = description;
        this.totalQuestions = totalQuestions;
        this.passingScore = passingScore;
        this.subject = subject;
        this.difficulty = difficulty;
        this.moduleId = null;
        this.createdAt = System.currentTimeMillis();
        this.updatedAt = System.currentTimeMillis();
        this.isArchived = false;
    }

    // Getters
    @NonNull
    public String getQuizId() { return quizId; }
    public String getUserId() { return userId; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public int getTotalQuestions() { return totalQuestions; }
    public double getPassingScore() { return passingScore; }
    public long getCreatedAt() { return createdAt; }
    public long getUpdatedAt() { return updatedAt; }
    public String getSubject() { return subject; }
    public int getDifficulty() { return difficulty; }
    public String getModuleId() { return moduleId; }
    public boolean isArchived() { return isArchived; }

    // Setters
    public void setQuizId(@NonNull String quizId) { this.quizId = quizId; }
    public void setUserId(String userId) { this.userId = userId; }
    public void setTitle(String title) { this.title = title; }
    public void setDescription(String description) { this.description = description; }
    public void setTotalQuestions(int totalQuestions) { this.totalQuestions = totalQuestions; }
    public void setPassingScore(double passingScore) { this.passingScore = passingScore; }
    public void setCreatedAt(long createdAt) { this.createdAt = createdAt; }
    public void setUpdatedAt(long updatedAt) { this.updatedAt = updatedAt; }
    public void setSubject(String subject) { this.subject = subject; }
    public void setDifficulty(int difficulty) { this.difficulty = difficulty; }
    public void setModuleId(String moduleId) { this.moduleId = moduleId; }
    public void setArchived(boolean archived) { isArchived = archived; }
}
